//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

/** @hidden */
public class _PremiumAccountPrxI extends com.zeroc.Ice._ObjectPrxI implements PremiumAccountPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
