//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

public class Credit implements java.lang.Cloneable,
                               java.io.Serializable
{
    public double cost;

    public Currency currency;

    public Date beginDate;

    public Date endDate;

    public Credit()
    {
        this.currency = Currency.PLN;
        this.beginDate = new Date();
        this.endDate = new Date();
    }

    public Credit(double cost, Currency currency, Date beginDate, Date endDate)
    {
        this.cost = cost;
        this.currency = currency;
        this.beginDate = beginDate;
        this.endDate = endDate;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Credit r = null;
        if(rhs instanceof Credit)
        {
            r = (Credit)rhs;
        }

        if(r != null)
        {
            if(this.cost != r.cost)
            {
                return false;
            }
            if(this.currency != r.currency)
            {
                if(this.currency == null || r.currency == null || !this.currency.equals(r.currency))
                {
                    return false;
                }
            }
            if(this.beginDate != r.beginDate)
            {
                if(this.beginDate == null || r.beginDate == null || !this.beginDate.equals(r.beginDate))
                {
                    return false;
                }
            }
            if(this.endDate != r.endDate)
            {
                if(this.endDate == null || r.endDate == null || !this.endDate.equals(r.endDate))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::BankClient::Credit");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, cost);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, currency);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, beginDate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, endDate);
        return h_;
    }

    public Credit clone()
    {
        Credit c = null;
        try
        {
            c = (Credit)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeDouble(this.cost);
        Currency.ice_write(ostr, this.currency);
        Date.ice_write(ostr, this.beginDate);
        Date.ice_write(ostr, this.endDate);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.cost = istr.readDouble();
        this.currency = Currency.ice_read(istr);
        this.beginDate = Date.ice_read(istr);
        this.endDate = Date.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Credit v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Credit ice_read(com.zeroc.Ice.InputStream istr)
    {
        Credit v = new Credit();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Credit> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Credit v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Credit> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Credit.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Credit _nullMarshalValue = new Credit();

    /** @hidden */
    public static final long serialVersionUID = -5610732269153164643L;
}
