//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

public class CreditInfo implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public Money localCost;

    public Money creditCost;

    public CreditInfo()
    {
        this.localCost = new Money();
        this.creditCost = new Money();
    }

    public CreditInfo(Money localCost, Money creditCost)
    {
        this.localCost = localCost;
        this.creditCost = creditCost;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CreditInfo r = null;
        if(rhs instanceof CreditInfo)
        {
            r = (CreditInfo)rhs;
        }

        if(r != null)
        {
            if(this.localCost != r.localCost)
            {
                if(this.localCost == null || r.localCost == null || !this.localCost.equals(r.localCost))
                {
                    return false;
                }
            }
            if(this.creditCost != r.creditCost)
            {
                if(this.creditCost == null || r.creditCost == null || !this.creditCost.equals(r.creditCost))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::BankClient::CreditInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, localCost);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, creditCost);
        return h_;
    }

    public CreditInfo clone()
    {
        CreditInfo c = null;
        try
        {
            c = (CreditInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        Money.ice_write(ostr, this.localCost);
        Money.ice_write(ostr, this.creditCost);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.localCost = Money.ice_read(istr);
        this.creditCost = Money.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CreditInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CreditInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        CreditInfo v = new CreditInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CreditInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CreditInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CreditInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CreditInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CreditInfo _nullMarshalValue = new CreditInfo();

    /** @hidden */
    public static final long serialVersionUID = 2876632936960995767L;
}
