//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

public enum Currency implements java.io.Serializable
{
    PLN(0),
    USD(1),
    EUR(2),
    AUD(3),
    CZK(4),
    DKK(5);

    public int value()
    {
        return _value;
    }

    public static Currency valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return PLN;
        case 1:
            return USD;
        case 2:
            return EUR;
        case 3:
            return AUD;
        case 4:
            return CZK;
        case 5:
            return DKK;
        }
        return null;
    }

    private Currency(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 5);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, Currency v)
    {
        if(v == null)
        {
            ostr.writeEnum(BankClient.Currency.PLN.value(), 5);
        }
        else
        {
            ostr.writeEnum(v.value(), 5);
        }
    }

    public static Currency ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(5);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Currency> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Currency v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<Currency> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static Currency validate(int v)
    {
        final Currency e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
