//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

public class InvalidPeselException extends com.zeroc.Ice.UserException
{
    public InvalidPeselException()
    {
        this.reason = "";
    }

    public InvalidPeselException(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public InvalidPeselException(String reason)
    {
        this.reason = reason;
    }

    public InvalidPeselException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::BankClient::InvalidPeselException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::BankClient::InvalidPeselException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 220598274196408030L;
}
