//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

public interface PremiumAccount extends Account
{
    CreditInfo takeCredit(Credit credit, com.zeroc.Ice.Current current)
        throws InvalidDateFormatException,
               UnsupportedCurrencyException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::BankClient::Account",
        "::BankClient::PremiumAccount",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::BankClient::PremiumAccount";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_takeCredit(PremiumAccount obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        _iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Credit iceP_credit;
        iceP_credit = Credit.ice_read(istr);
        inS.endReadParams();
        CreditInfo ret = obj.takeCredit(iceP_credit, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        CreditInfo.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "depositMoney",
        "getAccountBalance",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "takeCredit"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_depositMoney(this, in, current);
            }
            case 1:
            {
                return _iceD_getAccountBalance(this, in, current);
            }
            case 2:
            {
                return _iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return _iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return _iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return _iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_takeCredit(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
