//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `BankClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Java.Utils.BankClient;

public class UnsupportedCurrencyException extends com.zeroc.Ice.UserException
{
    public UnsupportedCurrencyException()
    {
        this.reason = "";
    }

    public UnsupportedCurrencyException(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public UnsupportedCurrencyException(String reason)
    {
        this.reason = reason;
    }

    public UnsupportedCurrencyException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::BankClient::UnsupportedCurrencyException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::BankClient::UnsupportedCurrencyException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -7178270032046606190L;
}
